In [60]:
print("hello world")

hello world

In [61]:
import numpy as np
import pandas as pd

In [62]:
a = np.array([1, 2, 3])
b = np.array(9)
c = np.array([[1, 2, 3, 5, 6]])

print(a, a.ndim) # vector 1 ndim
print(b, b.ndim) # scalar 0 ndim
print(c, c.ndim) # matrix 2 ndim

[1 2 3] 1
9 0
[[1 2 3 5 6]] 2

In [63]:
a = np.zeros((3, 4))

print(a, a.ndim) # matrix 2 ndim

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 2

In [64]:
b = np.ones((3, 4))

print(b, b.ndim) # matrix 2 ndim

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 2

In [65]:
c = np.eye(3)

print(c, c.ndim) # matrix 2 ndim

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 2

In [66]:
d = np.random.rand(3, 4)

print(d, d.ndim) # matrix 2 ndim

[[0.59186004 0.96708041 0.49902391 0.37917653]
 [0.85054737 0.87926533 0.28764688 0.67363599]
 [0.00887339 0.41037256 0.45103477 0.14202333]] 2

In [67]:
e = np.arange(10)

print(e, e.ndim) # vector 1 ndim

[0 1 2 3 4 5 6 7 8 9] 1

In [68]:
f = np.linspace(0, 1, 7)

print(f, f.ndim) # vector 1 ndim

[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ] 1

In [69]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

g = np.sum([a, b], axis=0)

print(g, g.ndim) # vector 1 ndim

[5 7 9] 1

# pandas

In [70]:
a = pd.Series([1, 2, 3, 4, 5])

print(a, a.ndim) # vector 1 ndim

0    1
1    2
2    3
3    4
4    5
dtype: int64 1

In [71]:
b = pd.DataFrame([1,2,3])

print(b, b.ndim) # matrix 2 ndim

   0
0  1
1  2
2  3 2

In [72]:
c = pd.DataFrame({
    "names":["John", "Alice", "Bob"], 
    "ages":[25, 30, 22]
    })

print(c, c.ndim) # matrix 2 ndim

   names  ages
0   John    25
1  Alice    30
2    Bob    22 2

In [73]:
df = pd.read_csv("Housing.csv")

df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,NaN,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960.0,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960.0,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500.0,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420.0,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000.0,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400.0,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620.0,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910.0,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850.0,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [74]:
print(df.isnull().sum()) # check for missing values

price               0
area                1
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [75]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              544 non-null    float64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    str
 6   guestroom         545 non-null    str
 7   basement          545 non-null    str
 8   hotwaterheating   545 non-null    str
 9   airconditioning   545 non-null    str
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    str
 12  furnishingstatus  545 non-null    str
dtypes: float64(1), int64(5), str(7)
memory usage: 55.5 KB

In [76]:
# df = df.dropna() # drop rows with missing values

In [77]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,NaN,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960.0,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960.0,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500.0,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420.0,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000.0,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400.0,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620.0,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910.0,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850.0,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [78]:
print(df.iloc[1:4]) # print first row

      price    area  bedrooms  bathrooms  stories mainroad guestroom basement  \
1  12250000  8960.0         4          4        4      yes        no       no
2  12250000  9960.0         3          2        2      yes        no      yes
3  12215000  7500.0         4          2        2      yes        no      yes

  hotwaterheating airconditioning  parking prefarea furnishingstatus
1              no             yes        3       no        furnished
2              no              no        2      yes   semi-furnished
3              no             yes        3      yes        furnished

In [79]:
print(df.loc[1]) # print first row

price                12250000
area                   8960.0
bedrooms                    4
bathrooms                   4
stories                     4
mainroad                  yes
guestroom                  no
basement                   no
hotwaterheating            no
airconditioning           yes
parking                     3
prefarea                   no
furnishingstatus    furnished
Name: 1, dtype: object

In [80]:
print(df.iloc[-1])

price                   1750000
area                     3850.0
bedrooms                      3
bathrooms                     1
stories                       2
mainroad                    yes
guestroom                    no
basement                     no
hotwaterheating              no
airconditioning              no
parking                       0
prefarea                     no
furnishingstatus    unfurnished
Name: 544, dtype: object

In [81]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,NaN,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960.0,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960.0,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500.0,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420.0,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [82]:

df.tail(10)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
535,2100000,3360.0,2,1,1,yes,no,no,no,no,1,no,unfurnished
536,1960000,3420.0,5,1,2,no,no,no,no,no,0,no,unfurnished
537,1890000,1700.0,3,1,2,yes,no,no,no,no,0,no,unfurnished
538,1890000,3649.0,2,1,1,yes,no,no,no,no,0,no,unfurnished
539,1855000,2990.0,2,1,1,no,no,no,no,no,1,no,unfurnished
540,1820000,3000.0,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400.0,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620.0,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910.0,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850.0,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [83]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,NaN,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960.0,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960.0,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500.0,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420.0,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000.0,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400.0,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620.0,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910.0,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850.0,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [ ]:
df = df.fillna(df["area"].mean()) # fill missing values with mean

print(df.info())

print(df.describe())



df

<class 'pandas.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    float64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    str
 6   guestroom         545 non-null    str
 7   basement          545 non-null    str
 8   hotwaterheating   545 non-null    str
 9   airconditioning   545 non-null    str
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    str
 12  furnishingstatus  545 non-null    str
dtypes: float64(1), int64(5), str(7)
memory usage: 55.5 KB

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,5146.369485,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960.000000,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960.000000,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500.000000,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420.000000,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000.000000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400.000000,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620.000000,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910.000000,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850.000000,3,1,2,yes,no,no,no,no,0,no,unfurnished